### ISSUE TITLE
can not cross compile in arm

### ISSUE THREAD

**Issue by van201314** [emeryberger/Hoard#18]
when i cross compilt it, it is error:
{standard input}: Assembler messages:
{standard input}:1118: Error: misaligned branch destination
{standard input}:1128: Error: misaligned branch destination
{standard input}:1132: Error: misaligned branch destination
{standard input}: Assembler messages:
{standard input}:356: Error: misaligned branch destination
{standard input}:366: Error: misaligned branch destination
{standard input}:370: Error: misaligned branch destination

any idea?

**Comment by tianacore** [comment]
Facing the same problem. used this command option. Reused the above with arm specific compiler
ARM_GCC_COMPILE = /abfdata/ks.giri/toolchain/arm-2010q1/bin/arm-none-linux-gnueabi-g++ -std=c++0x -fno-builtin-malloc -pipe -g $(CPPFLAGS) -fin    line-limit=20000 -finline-functions -DNDEBUG  $(INCLUDES) -D_REENTRANT=1 -shared $(GNU_SRC)  -Bsymbolic -o libhoard.so -ldl -lpthread

**Comment by tianacore** [comment]
The target CPU architecture is cortex ARMV7

**Comment by emeryberger** [comment]
What version of C++ compiler are you using?

**Comment by emeryberger** [comment]
I just successfully cross-compiled it with the following compiler:

```shell
$ arm-linux-gnueabihf-g++ --version
arm-linux-gnueabihf-g++ (Ubuntu/Linaro 4.9.2-10ubuntu10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by emeryberger** [comment]
Updated Makefile with appropriate command line for ARM cross-compilation (commit f7ea7217d8454416b7488cd8953498f7f7743171).
