### ISSUE TITLE
FreeBSD 10.1 loaded issue

### ISSUE THREAD

**Issue by ghost** [emeryberger/Hoard#20]
Hello,

I just install hoard on FreeBSD 10.1 when I set libhoard. Any idea what I'm doing wrong? 

root@localhost:~ # ldd /bin/ls
/bin/ls:
        libutil.so.9 => /lib/libutil.so.9 (0x800824000)
        libncurses.so.8 => /lib/libncurses.so.8 (0x800a36000)
        libc.so.7 => /lib/libc.so.7 (0x800c83000)
root@localhost:~ # setenv LD_PRELOAD /usr/local/lib/libhoard.so.1
root@localhost:~ # ldd /bin/ls
/bin/ls:
        libutil.so.9 => /lib/libutil.so.9 (0x800a83000)
        libncurses.so.8 => /lib/libncurses.so.8 (0x800c95000)
        libc.so.7 => /lib/libc.so.7 (0x800ee2000)
        libc++.so.1 => /usr/lib/libc++.so.1 (0x80128b000)
        libcxxrt.so.1 => /lib/libcxxrt.so.1 (0x80154b000)
        libm.so.5 => /lib/libm.so.5 (0x801767000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x80198f000)
        libthr.so.3 => /lib/libthr.so.3 (0x801b9d000)
root@localhost:~ #

**Comment by emeryberger** [comment]
Everything builds and runs fine on FreeBSD. `ldd` is not going to tell you anything useful. Hoard now prints a message indicating it's running; you can also see its effect by setting LD_PRELOAD and then running a benchmark application like `benchmarks/threadtest`.
