### ISSUE TITLE
Heap-Layers not included in release archives

### ISSUE THREAD

**Issue by mmcco** [emeryberger/Hoard#24]
Is this intentional?

**Comment by emeryberger** [comment]
Unfortunately, this is the stupid thing that Git does with submodules. I may just move a copy of Heap Layers into the repo; there's no other automatic way to deal with this.

**Comment by marcin-github** [comment]
Second proposal is create tagged release of Heap Layers. It could be easier to get second tarball and merge content with Hoard sources instead downloading tarball and then cloning Heap-Layers using git. Or Heap-Layers could be installed in /usr/include/Heap-Layers as build dependency of Hoard.

**Comment by emeryberger** [comment]
Heap Layers now downloads separately during the build process.
