### ISSUE TITLE
Runtime issues with Visual Studio 2015

### ISSUE THREAD

**Issue by varun85gupta** [emeryberger/Hoard#27]
I tried to build libhoard on windows with VS2015 using nmake. It built successfully. But when I try to run a sample program using hoard, It crashes in the following call stack : 

```
ntdll.dll!RtlReportCriticalFailure()    Unknown
ntdll.dll!RtlpReportHeapFailure()   Unknown
ntdll.dll!RtlpHeapHandleError() Unknown
ntdll.dll!RtlpLogHeapFailure()  Unknown
ntdll.dll!NtdllpFreeStringRoutine() Unknown
ntdll.dll!RtlFreeUnicodeString()    Unknown
ntdll.dll!LdrpSnapThunk()   Unknown
ntdll.dll!LdrGetProcedureAddressEx()    Unknown
ntdll.dll!LdrGetProcedureAddress()  Unknown
KernelBase.dll!GetProcAddress() Unknown
libhoard.dll!PatchMe() Line 594 C++
libhoard.dll!DllMain(void * hinstDLL, unsigned long fdwReason, void * lpreserved) Line 122
```

It's a simple program to allocate memory :

```
int main()
{
    char *str = NULL;
    int rc = ERROR;

    printf("Allocating a buffer...\n");
    str = (char*)malloc(MAX_BUF_SIZE*sizeof(char));

    if (str == NULL)
    {
        printf("Allocation of buffer failed !!! Exiting... \n");
        return ERROR;
    }

    strncpy(str, "Hello", 6);
    printf("Entered string is : %s\n", str);
    return OK;
}
```

It's a visual studio project where I added source/uselibhoard.cpp as additional source file and libhoard.lib in the linker options. Please check the attached screenshots.

![1](https://cloud.githubusercontent.com/assets/6773983/17276372/374c88a6-5745-11e6-8029-00e48c08239a.png)
![2](https://cloud.githubusercontent.com/assets/6773983/17276375/374fc2dc-5745-11e6-97a1-e89b7e3aa395.png)
![3](https://cloud.githubusercontent.com/assets/6773983/17276374/374d914c-5745-11e6-86e0-b9648358eff2.png)
![error](https://cloud.githubusercontent.com/assets/6773983/17276371/374bc8e4-5745-11e6-9ebe-abd5ec8df2e5.png)
![errorcode](https://cloud.githubusercontent.com/assets/6773983/17276373/374cf05c-5745-11e6-8cca-117189cd6f19.png)

**Comment by emeryberger** [comment]
Which version of Windows are you using?

**Comment by varun85gupta** [comment]
I am using Windows 2008 server R2.

**Comment by emeryberger** [comment]
This works for me on Windows 10 with the latest commits.
