### ISSUE TITLE
cannot allocate memory for thread-local data: ABORT

### ISSUE THREAD

**Issue by liu5320102** [emeryberger/Hoard#34]
it works in CentOS with some error,how to solve this problem...thanks

**Comment by emeryberger** [comment]
Can you provide a repro case? (That is, some code that demonstrates the problem.) Thanks.

**Comment by liu5320102** [comment]
I just use Hoard-3.10, becase my gcc is 4.4.7, take it up and the error is come... 

cannot allocate memory for thread-local data: ABORT

my server and complier info:
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


CentOS release 6.5 (Final)
Kernel \r on an \m


Linux hs-192-168-46-217 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux


core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 127451
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1024
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by emeryberger** [comment]
Please provide the exact steps (and programs) you used to trigger the error. Thanks.

**Comment by liu5320102** [comment]
Becase program is not coredump , i have no stacktrace revert where it confuse the ERROR

My program is very big...it has many modules(so)...and some modules cannot find source...I want use Hoard to improve my program...but it run for a moment and then program abort with the ERROR

I use glibc malloc and free,My program work is normal...

My program have 150 threads,is too many threads confuse this problem...

**Comment by emeryberger** [comment]
I suspect that you are out of swap space. I am not sure you will get a
usable core but try setting coresize to unlimited (ulimit -c unlimited) and
run it (hopefully you will get a core file and a useful stack trace).



--
Professor Emery Berger
College of Information and Computer Sciences
University of Massachusetts Amherst
www.emeryberger.org, @emeryberger

**Comment by emeryberger** [comment]
Any updates?

**Comment by emeryberger** [comment]
I am not able reproduce the problem on Ubuntu with the latest version. Closing.
