### ISSUE TITLE
Can`t build Hoard library on Windows

### ISSUE THREAD

**Issue by aPSopt** [emeryberger/Hoard#35]
I clone Horad by usage the link: 

> https://github.com/emeryberger/Hoard.git

Then as descibed in documentation I change directory to 

> C:\hoard\src

Then I try to build it:

> C:\hoard\src> nmake

And receive error:

> git clone https://github.com/emeryberger/Heap-Layers
> fatal: destination path 'Heap-Layers' already exists and is not an empty directory.

Its bug - the Heap-Layers already exist when I clone Hoard repo. Ok, I delete Heap-Layers folder and try to build again:

> C:\hoard\src> nmake

And receive followed error:

> source\libhoard.cpp(34): fatal error C1083: stdalign.h: No such file or directory

So at now the sources can not be compiled on the Windows platform. Could you fix it?

**Comment by emeryberger** [comment]
Thanks for the report! Fixed with https://github.com/emeryberger/Hoard/commit/addfe1b277ae9580ed54f7344f37c35981a3c44e.
