### ISSUE TITLE
Failed to allocate more than 2147483647 bytes of memory

### ISSUE THREAD

**Issue by rudreshahk** [emeryberger/Hoard#36]
I wanted to evaluate the Hoard for one of the project but i observed that Hoard fails to allocate more than 2GB of memory. I built the Hoard 3.12 with g++ version 4.9.0 on Linux.  Is there any limitation with the Hoard for the memory allocation. If not what could be wrong?
The allocation for 2147483647 bytes succeeds and allocation for 2147483648 onward fails.

Below are the g++ and Linux details:
```
	g++ --version
	g++ (GCC) 4.9.0 20130520 (experimental)
	Copyright (C) 2013 Free Software Foundation, Inc.
	This is free software; see the source for copying conditions.  There is NO
	warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
	uname -a
	Linux xxx.xxx.com 2.6.32-279.el6.x86_64 #1 SMP Fri Jun 22 12:19:21 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```

Attached here [AllocMem.zip](https://github.com/emeryberger/Hoard/files/1227416/AllocMem.zip) the sample program. Below the sample program output for allocations:

With Default gcc allocator:
```
	./AllocMem 2147483648
	Trying to allocate 2147483648 bytes of memory
	Successfully allocated 2147483648 bytes of memory
```

With Hoard Allocator:
```
	export LD_PRELOAD=/data/local/MemoryAllocators/Hoard/libhoard.so
	./AllocMem 2147483648
	Trying to allocate 2147483648 bytes of memory
	Failed to allocate 2147483648 bytes of memory
```

**Comment by emeryberger** [comment]
Thanks for the report. Fixed with latest commit to Heap Layers (in short, it still prevents such large requests on 32-bit platforms, but allows larger allocations on 64-bit platforms).

**Comment by rudreshahk** [comment]
Thanks @emeryberger. I tried the Hoard-master source to get the 2GB limit fix. But my MPI application failed with the below error:
`Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(420)..............:
MPID_Init(180).....................: channel initialization failed
MPIDI_CH3_Init(38).................:
MPID_nem_init(244).................:
MPID_nem_tcp_init(108).............:
MPID_nem_tcp_get_business_card(354):
MPID_nem_tcp_init(313).............: gethostbyname failed, myHostName.com (errno 3)
`

MPI Details:
`
MPICH 1.5 built using gcc5.4
`

MPI application and the Hoard are also built using gcc5.4. 

But note that the Hoard3.12 was working fine with the same MPI application but that had the limitation of 2GB memory allocation.

**Comment by boegel** [comment]
For anyone bumping into this, it seems like this is the fix that @emeryberger refered to: https://github.com/emeryberger/Heap-Layers/commit/38063a47183fe79fa3be719992db0ce2f37ac093
