### ISSUE TITLE
Please remove the -g flag in the GNUMakefile for non debug builds.

### ISSUE THREAD

**Issue by sirilvk** [emeryberger/Hoard#37]
Please remove the -g flag in the GNUMakefile for non debug builds. Could see a performance improvement without that. (also looks like a typo in section LINUX_GCC_x86_64_COMPILE ).

**Comment by emeryberger** [comment]
Generating debug symbols should have no effect on performance (-DNDEBUG disables assertions, which _does_ have an impact); compiler optimizations should be unaffected.

What is the typo?

**Comment by sirilvk** [comment]
Thought it would have been a mistake since it was in all the build configs. Also surprisingly after removing -g on Ubuntu server 17.10 x64 build I got a slightly faster execution time for my application. However closing this issue. Sorry for the inconvenience.
