### ISSUE TITLE
Extending the HoardSuperblock to support different headers

### ISSUE THREAD

**Issue by iyzhang** [emeryberger/Hoard#40]
Hi,

I'd like to be able to add additional fields to the HoardSuperblock header. If the Header were passed as a template parameter, that would be easy.

Thanks,
Irene

**Comment by emeryberger** [comment]
Forgot to close (implemented with https://github.com/emeryberger/Hoard/commit/baa62abb7eb873bd40068fbb96f44d7939164a20).
