### ISSUE TITLE
Use -install_name on macOS

### ISSUE THREAD

**Issue by ryandesign** [emeryberger/Hoard#41]
Your library is being built without the `install_name` being set, which means that it cannot be used unless the user manually fixes the `install_name` later using `install_name_tool`.

You have instructions about setting `DYLD_INSERT_LIBRARIES` to the path where the library is, which would be unnecessary if you set the `install_name` to the place where the library will be installed.

You could do this by adding `-install_name $(PREFIX)/libhoard.dylib` to `MACOS_COMPILE` and `MACOS_COMPILE_DEBUG` in GNUmakefile.

**Comment by emeryberger** [comment]
(Using `$(DESTDIR)$(PREFIX)`)

Fixed with https://github.com/emeryberger/Hoard/commit/618719b9ab3a2546a6cf4ff9f4ed3d0b07a1420c. Thanks for the suggestion.
