### ISSUE TITLE
Support DESTDIR

### ISSUE THREAD

**Issue by ryandesign** [emeryberger/Hoard#42]
You currently install your library with e.g.

```
cp libhoard.dylib $(PREFIX)
```

This assumes `$(PREFIX)` is writable. It might not be in the context of a package management system that wants to stage the files in a temporary location first.

You should support the standard `$(DESTDIR)` variable for this, by changing these copy commands to e.g.

```
cp libhoard.dylib $(DESTDIR)$(PREFIX)
```

**Comment by emeryberger** [comment]
Fixed with https://github.com/emeryberger/Hoard/commit/6d858bb034762b1c60dbbba3a6bf18749359782b.
Thanks.
