### ISSUE TITLE
Turn off banner in STDERR

### ISSUE THREAD

**Issue by poige** [emeryberger/Hoard#48]
I don't really find it any useful or even common for allocators to report they're being put in use, what's the logical reasoning behind it?

**Comment by poige** [comment]
No one else is doing that.

For those who need details there's `pmap` that handles most of cases.

**Comment by emeryberger** [comment]
Fair enough. Certainly not a problem to disable it.

**Comment by emeryberger** [comment]
Disabled with https://github.com/emeryberger/Hoard/commit/de06b8b79b06a7e52caf1b7187419af9c57ea43e
