### ISSUE TITLE
Fix SIGSEGV

### ISSUE THREAD

**Issue by poige** [emeryberger/Hoard#49]
3.12 is just failing when LD_PRELOADed <s>on Ubuntu Linux 16.04 LTS</s> — on literally any executables' run.

Is Hoard alive at all? I understand that tcmalloc outperforms it a bit (and is under active development for sure) but it'd be great to know the status for sure as well.

**Comment by emeryberger** [comment]
Very much alive.

Did you pull and build from HEAD? Please provide the name of one executable that fails. I just built Hoard on Ubuntu and ran a few executables without any issues.

**Comment by emeryberger** [comment]
Thanks for the clarification. I just successfully built Hoard (and tested it, works fine AFAICT) on CentOS 7 (after installing updated development tools). Given that version 7 has been out since 2014, I think it doesn't make sense to support CentOS 6 at this point, so I am closing this.
