### ISSUE TITLE
always_inline breaks on Windows

### ISSUE THREAD

**Issue by blattersturm** [emeryberger/Hoard#56]
#54 seems to be breaking the Windows build as MSVC won't understand always_inline or gnuwrapper code.

**Comment by emeryberger** [comment]
Can you post the error message? In theory, the changes made in that commit should only affect Linux and Mac (see the `#if defined` on line 127).

**Comment by blattersturm** [comment]
The code affected in `libhoard.cpp` from that PR does seem to be included in the Windows build but it might have been my fault with build system integration or I incorrectly `blame`'d it.

**Comment by valeskas** [comment]
I think it was intended to be "#if defined", not "#if !defined"
```
#if !defined(__GNUG__)
  void * __attribute__((always_inline)) xxmalloc (size_t sz) {
#else
```

**Comment by stikdragon** [comment]
I'm also experiencing this under VS 2019

**Comment by emeryberger** [comment]
Thanks for the note. Please give it a try again and see what happens - thanks!

**Comment by stikdragon** [comment]
Spot on, thanks :-)
