### ISSUE TITLE
Compiling : what c2s() in geometricsizeclass ?

### ISSUE THREAD

**Issue by mprevot** [emeryberger/Hoard#63]
It seems that c2s() is `bool c2s(int)`, but I could not see any definition anywhere in Hoard. I'm compiling in Visual Studio 2019 Hoard as a c++ (or c) project.

https://github.com/emeryberger/Hoard/blob/5afe855606e60ba255915d5cd816474815fc8844/src/include/hoard/geometricsizeclass.cpp#L22

https://github.com/emeryberger/Hoard/blob/5afe855606e60ba255915d5cd816474815fc8844/src/include/hoard/geometricsizeclass.cpp#L28

What does `c2s()` do ? Which one should I use ?

**Comment by emeryberger** [comment]
It's defined in `src/include/hoard/geometricsizeclass.h`:

https://github.com/emeryberger/Hoard/blob/5afe855606e60ba255915d5cd816474815fc8844/src/include/hoard/geometricsizeclass.h#L126
https://github.com/emeryberger/Hoard/blob/5afe855606e60ba255915d5cd816474815fc8844/src/include/hoard/geometricsizeclass.h#L127
