### ISSUE TITLE
Status of Hoard?

### ISSUE THREAD

**Issue by somehowchris** [emeryberger/Hoard#69]
Hey :)

Since I can not see any discussions tab I'm going to ask this one hear.

I have heard of Hoard and was about to look into it, whats it's current status? From my point of view there are no comments on other issues, PRs and no new-ish commits. Does it work properly?

**Comment by emeryberger** [comment]
Hi - sorry for the delayed response. Hoard continues to work well on Mac OS (x86 and M1) and Linux (and I just merged some recent PRs and pushed an update).
